# Generated by Django 4.2.4 on 2023-08-09 19:03

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("pfg_img", models.ImageField(upload_to="pfg_images")),
                ("pbg_img", models.ImageField(upload_to="png_images")),
                ("about", models.TextField()),
                ("location", models.CharField(max_length=20)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("tittle", models.CharField(max_length=100)),
                ("post_img", models.ImageField(upload_to="post_images")),
                ("post_disc", models.TextField()),
                ("category", models.CharField(max_length=10)),
                ("time_stamp", models.DateTimeField(auto_now_add=True)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        populate_from="tittle",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "userprofile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="posts.userprofile",
                    ),
                ),
            ],
        ),
    ]
