# Generated by Django 4.2.4 on 2023-08-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_alter_post_category_alter_post_tittle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_img",
            field=models.ImageField(blank=True, null=True, upload_to="post_images"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="pbg_img",
            field=models.ImageField(blank=True, null=True, upload_to="png_images"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="pfg_img",
            field=models.ImageField(blank=True, null=True, upload_to="pfg_images"),
        ),
    ]
