# Generated by Django 4.2.4 on 2023-08-17 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_alter_post_post_img_alter_userprofile_pbg_img_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Followers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=30)),
                ("follow", models.CharField(max_length=30)),
            ],
        ),
    ]
