# Generated by Django 4.2.4 on 2023-08-17 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0007_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="commenter",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                to="posts.userprofile",
            ),
            preserve_default=False,
        ),
    ]
