# Generated by Django 4.2.4 on 2023-08-18 04:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0008_comments_commenter"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReplyComments",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("replycomment", models.TextField()),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="posts.comments"
                    ),
                ),
                (
                    "replycommenter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="posts.userprofile",
                    ),
                ),
            ],
        ),
    ]
